### ISSUE TITLE
Search option and debug

### ISSUE THREAD

**Issue by Vouivre** [kisslinux/kiss#109]
Hello, 

I'm almost sure something changed in `kiss` for the search option and for debugging. 

I have in mind it was possible to search a package with a wildcard, like

````
kiss search zath*
````

But if I do that search, I get:

````
!> Arguments contain invalid characters: '!*[]'
````

Escaping the `*` changes nothing and searching only `zath` doesn't find `zathura` for example. 

Second, sometimes I want to debug some packages with `export KISS_DEBUG=1`. Before some folders `build-xxxx` and `extract-xxxx` were created. They aren't created anymore. For example if I build a package, the following messages are displayed:

````
make[1]: Leaving directory '/home/user/.cache/kiss/build-5527/cups/cups'
Making all in tools...
make[1]: warning: -j8 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/home/user/.cache/kiss/build-5527/cups/tools'
````

But I can't find any folder `build-5527` in the cache directory. 

I have seen in the code of `kiss` that you catch some signals sometimes. Usually, when I'm creating a package, I use `export KISS_DEBUG=1`, then I start the build and I stop it before it's finished with `Ctrl + C`. Everything is then decompressed in a folder. 

Is it the expected behavior ?

**Comment by dylanaraps** [comment]
Fixed all of your issues. :)

Thanks for letting me know.

**Comment by Vouivre** [comment]
Great, thank you! :+1:

**Comment by Vouivre** [comment]
Hello, 

I have the version 1.4.1 of `kiss`. The issue is still there, unfortunately. Did you fix something in 1.4.2 ?
